import type { Metadata } from "next"
import "./globals.css"
import AppClerkProvider from "@/components/AppClerkProvider"
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import LoaderProvider from "@/components/loader/LoaderProvider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "anamol hasan",
  description: "Generated by create fullstack app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body>
        <AppClerkProvider>
          <LoaderProvider>
            {children}
          </LoaderProvider>
        </AppClerkProvider>
      </body>
    </html>
  )
}